version: '3.8'

services:
  selenium-gpt:
    image: leviosa/selenium-gpt:latest
    shm_size: '2g'
    container_name: SeleniumGPT
    restart: no
    ports:
      - "7900:7900"    # noVNC
      - "15001:15001"  # SeleniumChatGPTServer service listen port
    environment:
      PORT: 15001
      # DISPLAY: "orangepi-2.local:0"
      # DISPLAY: "192.168.1.42:0"
      DISPLAY: ":99.0"
      # HTTP_PROXY: ""
      # HTTP_PROXY: ""
    volumes:
      - ./chrome_user_data:/home/seluser/user_data_dir
      - ./debug:/home/seluser/debug

